### PR TITLE
Minimized version of pull-to-reload

### PR DESCRIPTION
**Pull request by mdczaplicki**
Not much to say

### CODE REVIEW

**Comment by ErlendEllingsen** [comment]
Thanks. This addition now requires that all future releases must include a minified version. Which software / compression / minifier did you use?

**Comment by ErlendEllingsen** [comment]
@mdczaplicki

**Comment by mdczaplicki** [comment]
Hey, yeah sure. Now after every change you need to minify. As you can see
it is almost twice as lighter as normal version.
Easiest to use is https://jscompress.com/ or any other online. But
sometimes code may be stored somewhere on the server - so might not be the
best option to use for some closed-source projects.
You can either use this one - https://github.com/mishoo/UglifyJS - it is
much more advanced.

**Comment by ErlendEllingsen** [comment]
Yeah I am using UglifyJS for most of my projects😄 just wanted to check what you used

**Comment by mdczaplicki** [comment]
For this one - I have used online tool :)

**Pull request merged**
